apiVersion: batch/v1
kind: Job
metadata:
  name: job-task-queue-consumer-worker-2
spec:
  parallelism: 2
  template:
    metadata:
      name: job-task-queue-consumer-worker-2
    spec:
      volumes:
      - name: video-upload-minikube-pv-volume
        persistentVolumeClaim:
          claimName: video-upload-minikube-pv-volume-claim

      containers:
      - name: c
        image: n1207n/video-transcode-platform/task_queue/consumer:dev
        imagePullPolicy: Never

        volumeMounts:
          - mountPath: "/data/video_uploads/"
            name: video-upload-minikube-pv-volume

        env:
          - name: GET_HOSTS_FROM
            value: dns
          - name: REDIS_URL
            value: "queue-storage-redis"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_TOPIC
            valueFrom:
              secretKeyRef:
                name: redis-queue-info
                key: queue-topic
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: queue-storage-redis
                key: redis-password
          - name: UPLOAD_FOLDER_PATH
            value: /data/video_uploads/

      restartPolicy: OnFailure
