apiVersion: v1
kind: Service

metadata:
  name: transcoder-api
  labels:
    name: transcoder-api
    tier: backend

spec:
  ports:
    - port: 8800
      targetPort: 8800
      protocol: TCP
  selector:
    name: transcoder-api
    tier: backend
