apiVersion: v1
kind: Service

metadata:
  name: nginx-proxy
  labels:
    name: nginx-proxy
    tier: backend

spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: nginx-proxy
    tier: backend
