apiVersion: extensions/v1beta1

kind: Deployment

metadata:
  name: nginx-proxy
  labels:
    name: nginx-proxy
    tier: backend

spec:
  replicas: 1

  template:
    metadata:
      labels:
        name: nginx-proxy
        tier: backend

    spec:
      containers:
        - name: nginx
          image: n1207n/video-transcode-queue/nginx_proxy:dev
          imagePullPolicy: Never

          ports:
            - containerPort: 80
              name: nginx
