apiVersion: batch/v1
kind: Job
metadata:
  name: job-task-queue-consumer-worker-2
spec:
  parallelism: 2
  template:
    metadata:
      name: job-task-queue-consumer-worker-2
    spec:
      containers:
      - name: c
        image: n1207n/video-transcode-queue/task_queue/consumer:dev
        imagePullPolicy: Never
        env:
          - name: GET_HOSTS_FROM
            value: dns
          - name: REDIS_URL
            value: "queue-storage-redis"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_TOPIC
            valueFrom:
              secretKeyRef:
                name: redis-queue-info
                key: queue-topic
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: queue-storage-redis
                key: redis-password
      restartPolicy: OnFailure
