apiVersion: v1
kind: Service

metadata:
  name: video-api
  labels:
    name: video-api
    tier: backend

spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    name: video-api
    tier: backend
