apiVersion: extensions/v1beta1

kind: Deployment

metadata:
  name: video-api
  labels:
    name: video-api
    tier: backend

spec:
  replicas: 1

  template:
    metadata:
      labels:
        name: video-api
        tier: backend

    spec:
      volumes:
      - name: video-upload-minikube-pv-volume
        persistentVolumeClaim:
          claimName: video-upload-minikube-pv-volume-claim

      containers:
        - name: video-api
          image: n1207n/video-transcode-queue/video_backend_api:dev
          imagePullPolicy: Never

          volumeMounts:
            - mountPath: "/data/video_uploads/"
              name: video-upload-minikube-pv-volume

          command: ["ash"]
          args: ["-c", "/go/bin/api_server"]

          ports:
            - containerPort: 8080
              name: video-api

          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: PGDB
              value: video_app
            - name: PGUSER
              value: video_app
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-database-postgresql
                  key: postgres-password
            - name: PGHOST
              value: app-database-postgresql:5432
            - name: QUEUE_TOPIC
              valueFrom:
                secretKeyRef:
                  name: redis-queue-info
                  key: queue-topic
            - name: UPLOAD_FOLDER_PATH
              value: /data/video_uploads/
