kind: PersistentVolume
apiVersion: v1

metadata:
  name: video-upload-minikube-pv-volume
  labels:
    type: local

spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/video_uploads"
